function description(data) {
elementOpen("div", null, null, "title", data.title)
  elementOpen("div", null, ["class", data.cssClass])
  elementClose("div")
  text(" \
    My name is " + data.name + " my age is " + data.age + " \
    I live at " + data.address + " \
   \
    ")
  elementOpen("span", null, null, "title", JSON.stringify(data))
    text("Hi")
  elementClose("span")
  elementOpen("input", null, ["type", "text", "onchange", data.onChange], "value", data.val)
  elementClose("input")
  if (data.showMe) {
    elementOpen("p")
      elementOpen("span", null, ["style", { color: data.foo, backgroundColor: data.bar }])
        text(data.name)
      elementClose("span")
      elementOpen("span", null, null, "class", data.bar + ' other-css')
        text("description")
      elementClose("span")
      elementOpen("input", null, ["type", "text"], "disabled", data.isDisabled)
      elementClose("input")
    elementClose("p")
  }
  elementOpen("ul")
    ;(Array.isArray(data.items) ? data.items : Object.keys(data.items)).forEach(function(item, index) {
      elementOpen("li", "item in data.items" + index)
        elementOpen("span", null, null, "class",  $index % 2 ? 'odd' : 'even' )
          text($index)
        elementClose("span")
        elementOpen("span")
          text(item.foo)
        elementClose("span")
        elementOpen("input", null, null, "value", item.name)
        elementClose("input")
      elementClose("li")
    }, data.items)
  elementClose("ul")
  elementOpen("ul")
    ;(Array.isArray(data.arr) ? data.arr : Object.keys(data.arr)).forEach(function(item, index) {
      elementOpen("li", "item in data.arr" + index)
        elementOpen("span")
          text(item)
        elementClose("span")
        elementOpen("span")
          text($index)
        elementClose("span")
        elementOpen("span")
          text(data.arr[item])
        elementClose("span")
      elementClose("li")
    }, data.arr)
  elementClose("ul")
  elementOpen("ul")
    ;(Array.isArray(data.obj) ? data.obj : Object.keys(data.obj)).forEach(function(key, index) {
      elementOpen("li", "key in data.obj" + index)
        elementOpen("span")
          text(key)
        elementClose("span")
        elementOpen("span")
          text(index)
        elementClose("span")
        elementOpen("span")
          text(this[key])
        elementClose("span")
      elementClose("li")
    }, data.obj)
  elementClose("ul")
elementClose("div")
};
