module.exports = function() {
  elementOpen("tr", "item in items" + $index)
    elementOpen("td")
      text("" + item.product.productId + "")
    elementClose("td")
    elementOpen("td")
      text("" + item.product.productName + "")
    elementClose("td")
    elementOpen("td")
      elementOpen("input", null, ["type", "number", "onchange", function() {item.quantity = this.value}], "value", item.quantity)
      elementClose("input")
    elementClose("td")
    elementOpen("td")
      text("" + item.product.price + "")
    elementClose("td")
    elementOpen("td")
      text("" + item.product.discountPercent * 100 + ' %' + "")
    elementClose("td")
    elementOpen("td")
      text("" + item.cost.toFixed(2) + "")
    elementClose("td")
    elementOpen("td")
      elementOpen("button", null, ["onclick", function() { items.splice($index, 1)} ])
        text("Remove")
      elementClose("button")
    elementClose("td")
  elementClose("tr")
}
